default: &default
  app:
    demo_mode: <%= ENV.fetch("DEMO_MODE") { true } %>
  mailer:
    postmark_api_key: <%= ENV.fetch("POSTMARK_API_TOKEN") { '' } %>
    default_site_host: <%= ENV.fetch("DEFAULT_SITE_HOST_ADDRESS") { '' } %>
    default_from: <%= ENV.fetch("DEFAULT_FROM_EMAIL") { 'from@example.com' } %>
    host: <%= ENV["MAIL_HOST"] %>
    port: <%= ENV["MAIL_PORT"] || '587' %>
    domain: <%= ENV["APP_DOMAIN_NAME"] %>
    user_name: <%= ENV["MAIL_USER_NAME"] %>
    password: <%= ENV["MAIL_PASSWORD"] %>
    authentication: "plain"
    enable_starttls_auto: true

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
