default: &default
  app:
    demo_mode: <%= ENV.fetch("DEMO_MODE") { true } %>
  mailer:
    postmark_api_key: <%= ENV.fetch("POSTMARK_API_TOKEN") { '' } %>
    default_site_host: <%= ENV.fetch("DEFAULT_SITE_HOST_ADDRESS") { '' } %>
    default_from: <%= ENV.fetch("DEFAULT_FROM_EMAIL") { 'from@example.com' } %>

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
